export const PAISES = [
  { value: 'BR', label: 'Brasil' },
  { value: 'AR', label: 'Argentina' },
  { value: 'UY', label: 'Uruguai' },
  { value: 'PY', label: 'Paraguai' },
  { value: 'CL', label: 'Chile' },
  { value: 'CO', label: 'Colômbia' },
  { value: 'PE', label: 'Peru' },
  { value: 'BO', label: 'Bolívia' },
  { value: 'EC', label: 'Equador' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'US', label: 'Estados Unidos' },
  { value: 'MX', label: 'México' },
  { value: 'PT', label: 'Portugal' },
  { value: 'ES', label: 'Espanha' },
  { value: 'IT', label: 'Itália' },
  { value: 'FR', label: 'França' },
  { value: 'DE', label: 'Alemanha' },
  { value: 'GB', label: 'Reino Unido' },
  { value: 'JP', label: 'Japão' },
  { value: 'CN', label: 'China' },
];

export const ESTADOS_BRASILEIROS = [
  { value: 'AC', label: 'Acre' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso' },
  { value: 'MS', label: 'Mato Grosso do Sul' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia' },
  { value: 'RR', label: 'Roraima' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' },
];

export const CIDADES_BRASILEIRAS = [
  { value: 'sao-paulo-sp', label: 'São Paulo - SP' },
  { value: 'rio-de-janeiro-rj', label: 'Rio de Janeiro - RJ' },
  { value: 'brasilia-df', label: 'Brasília - DF' },
  { value: 'salvador-ba', label: 'Salvador - BA' },
  { value: 'fortaleza-ce', label: 'Fortaleza - CE' },
  { value: 'belo-horizonte-mg', label: 'Belo Horizonte - MG' },
  { value: 'manaus-am', label: 'Manaus - AM' },
  { value: 'curitiba-pr', label: 'Curitiba - PR' },
  { value: 'recife-pe', label: 'Recife - PE' },
  { value: 'goiania-go', label: 'Goiânia - GO' },
  { value: 'belem-pa', label: 'Belém - PA' },
  { value: 'porto-alegre-rs', label: 'Porto Alegre - RS' },
  { value: 'guarulhos-sp', label: 'Guarulhos - SP' },
  { value: 'campinas-sp', label: 'Campinas - SP' },
  { value: 'sao-luis-ma', label: 'São Luís - MA' },
  { value: 'sao-goncalo-rj', label: 'São Gonçalo - RJ' },
  { value: 'maceio-al', label: 'Maceió - AL' },
  { value: 'duque-de-caxias-rj', label: 'Duque de Caxias - RJ' },
  { value: 'natal-rn', label: 'Natal - RN' },
  { value: 'teresina-pi', label: 'Teresina - PI' },
  { value: 'campo-grande-ms', label: 'Campo Grande - MS' },
  { value: 'sao-bernardo-do-campo-sp', label: 'São Bernardo do Campo - SP' },
  { value: 'joao-pessoa-pb', label: 'João Pessoa - PB' },
  { value: 'santo-andre-sp', label: 'Santo André - SP' },
  { value: 'osasco-sp', label: 'Osasco - SP' },
  { value: 'ribeirao-preto-sp', label: 'Ribeirão Preto - SP' },
  { value: 'uberlandia-mg', label: 'Uberlândia - MG' },
  { value: 'sorocaba-sp', label: 'Sorocaba - SP' },
  { value: 'contagem-mg', label: 'Contagem - MG' },
  { value: 'aracaju-se', label: 'Aracaju - SE' },
  { value: 'feira-de-santana-ba', label: 'Feira de Santana - BA' },
  { value: 'cuiaba-mt', label: 'Cuiabá - MT' },
  { value: 'joinville-sc', label: 'Joinville - SC' },
  { value: 'aparecida-de-goiania-go', label: 'Aparecida de Goiânia - GO' },
  { value: 'londrina-pr', label: 'Londrina - PR' },
  { value: 'juiz-de-fora-mg', label: 'Juiz de Fora - MG' },
  { value: 'ananindeua-pa', label: 'Ananindeua - PA' },
  { value: 'niteroi-rj', label: 'Niterói - RJ' },
  { value: 'porto-velho-ro', label: 'Porto Velho - RO' },
  { value: 'serra-es', label: 'Serra - ES' },
  { value: 'caxias-do-sul-rs', label: 'Caxias do Sul - RS' },
  { value: 'florianopolis-sc', label: 'Florianópolis - SC' },
  { value: 'macapa-ap', label: 'Macapá - AP' },
  { value: 'vitoria-es', label: 'Vitória - ES' },
  { value: 'rio-branco-ac', label: 'Rio Branco - AC' },
  { value: 'boa-vista-rr', label: 'Boa Vista - RR' },
  { value: 'palmas-to', label: 'Palmas - TO' },
];
