export interface GlobalTheme {
  id: string;
  name: string;
  emoji: string;
  description: string;
  colors: {
    pageBackground: string;
    cardBackground: string;
    primary: string;
    primaryForeground: string;
    accent: string;
    accentForeground: string;
    text: string;
    textMuted: string;
    border: string;
    muted: string;
  };
}

export const GLOBAL_THEMES: GlobalTheme[] = [
  {
    id: 'light',
    name: 'Tema Claro',
    emoji: '☀️',
    description: 'Limpo e luminoso',
    colors: {
      pageBackground: '#F8FAFC',
      cardBackground: '#FFFFFF',
      primary: '#3B82F6',
      primaryForeground: '#FFFFFF',
      accent: '#60A5FA',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#6B7280',
      border: '#E5E7EB',
      muted: '#F3F4F6',
    },
  },
  {
    id: 'gray',
    name: 'Tema Médio',
    emoji: '🌥️',
    description: 'Equilibrado e neutro',
    colors: {
      pageBackground: '#9CA3AF',
      cardBackground: '#F3F4F6',
      primary: '#4B5563',
      primaryForeground: '#FFFFFF',
      accent: '#6B7280',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#D1D5DB',
      muted: '#E5E7EB',
    },
  },
  {
    id: 'dark',
    name: 'Tema Escuro',
    emoji: '🌙',
    description: 'Moderno e elegante',
    colors: {
      pageBackground: '#1F2937',
      cardBackground: '#374151',
      primary: '#60A5FA',
      primaryForeground: '#FFFFFF',
      accent: '#3B82F6',
      accentForeground: '#FFFFFF',
      text: '#F9FAFB',
      textMuted: '#D1D5DB',
      border: '#4B5563',
      muted: '#4B5563',
    },
  },
  {
    id: 'ocean',
    name: 'Azul Oceano',
    emoji: '🌊',
    description: 'Profissional e calmo',
    colors: {
      pageBackground: '#7DD3FC',
      cardBackground: '#FFFFFF',
      primary: '#0369A1',
      primaryForeground: '#FFFFFF',
      accent: '#0EA5E9',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#BAE6FD',
      muted: '#E0F2FE',
    },
  },
  {
    id: 'forest',
    name: 'Verde Floresta',
    emoji: '🌲',
    description: 'Natural e fresco',
    colors: {
      pageBackground: '#86EFAC',
      cardBackground: '#FFFFFF',
      primary: '#15803D',
      primaryForeground: '#FFFFFF',
      accent: '#10B981',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#BBF7D0',
      muted: '#DCFCE7',
    },
  },
  {
    id: 'purple',
    name: 'Roxo Noturno',
    emoji: '🌙',
    description: 'Criativo e moderno',
    colors: {
      pageBackground: '#C084FC',
      cardBackground: '#FFFFFF',
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      accent: '#A855F7',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#E9D5FF',
      muted: '#F3E8FF',
    },
  },
  {
    id: 'energy',
    name: 'Vermelho Energia',
    emoji: '🔥',
    description: 'Dinâmico e vibrante',
    colors: {
      pageBackground: '#FCA5A5',
      cardBackground: '#FFFFFF',
      primary: '#B91C1C',
      primaryForeground: '#FFFFFF',
      accent: '#F97316',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#FECACA',
      muted: '#FEE2E2',
    },
  },
  {
    id: 'solar',
    name: 'Amarelo Solar',
    emoji: '☀️',
    description: 'Alegre e energético',
    colors: {
      pageBackground: '#FDE047',
      cardBackground: '#FFFFFF',
      primary: '#CA8A04',
      primaryForeground: '#FFFFFF',
      accent: '#FBBF24',
      accentForeground: '#1F2937',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#FEF08A',
      muted: '#FEF9C3',
    },
  },
  {
    id: 'pink',
    name: 'Rosa Suave',
    emoji: '🌸',
    description: 'Delicado e acolhedor',
    colors: {
      pageBackground: '#F9A8D4',
      cardBackground: '#FFFFFF',
      primary: '#DB2777',
      primaryForeground: '#FFFFFF',
      accent: '#F472B6',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#FBCFE8',
      muted: '#FCE7F3',
    },
  },
  {
    id: 'turquoise',
    name: 'Turquesa Tropical',
    emoji: '🏝️',
    description: 'Refrescante e moderno',
    colors: {
      pageBackground: '#5EEAD4',
      cardBackground: '#FFFFFF',
      primary: '#0F766E',
      primaryForeground: '#FFFFFF',
      accent: '#14B8A6',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#99F6E4',
      muted: '#CCFBF1',
    },
  },
  {
    id: 'corporate',
    name: 'Cinza Corporativo',
    emoji: '🌆',
    description: 'Sóbrio e profissional',
    colors: {
      pageBackground: '#D1D5DB',
      cardBackground: '#FFFFFF',
      primary: '#4B5563',
      primaryForeground: '#FFFFFF',
      accent: '#6B7280',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#E5E7EB',
      muted: '#F3F4F6',
    },
  },
  {
    id: 'orange',
    name: 'Laranja Vibrante',
    emoji: '🍊',
    description: 'Criativo e amigável',
    colors: {
      pageBackground: '#FDBA74',
      cardBackground: '#FFFFFF',
      primary: '#C2410C',
      primaryForeground: '#FFFFFF',
      accent: '#F97316',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#FED7AA',
      muted: '#FFEDD5',
    },
  },
  {
    id: 'royal',
    name: 'Azul Real',
    emoji: '💙',
    description: 'Confiável e elegante',
    colors: {
      pageBackground: '#93C5FD',
      cardBackground: '#FFFFFF',
      primary: '#1E40AF',
      primaryForeground: '#FFFFFF',
      accent: '#3B82F6',
      accentForeground: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#374151',
      border: '#BFDBFE',
      muted: '#DBEAFE',
    },
  },
];
